version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/gym/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60


        #version: 0.0: CodeDeploy appspec 파일 버전을 지정합니다. 현재 사용 중인 버전은 0.0입니다.

        #os: linux: 배포 대상 인스턴스의 운영 체제를 지정합니다. 이 경우 Linux 운영 체제를 사용하고 있습니다.

        #files: 배포할 파일 및 디렉토리를 정의하는 섹션입니다.

        #source: 배포할 파일 또는 디렉토리의 원본 경로를 지정합니다. 이 경우 / 경로의 모든 파일과 디렉토리를 배포하겠다는 의미입니다.
        #destination: 파일 또는 디렉토리를 배포할 대상 경로를 지정합니다. 이 경우 배포된 파일 및 디렉토리를 /home/ec2-user/cicdproject 경로로 배포합니다.
        #permissions: 배포된 파일 및 디렉토리의 권한을 설정하는 섹션입니다.

        #object: 권한을 설정할 파일 또는 디렉토리의 경로를 지정합니다. 이 경우 /home/ec2-user/cicdproject/ 경로의 권한을 설정합니다.
        #owner: 파일 또는 디렉토리의 소유자를 지정합니다. 이 경우 파일과 디렉토리는 ec2-user 소유자가 됩니다.
        #group: 파일 또는 디렉토리의 그룹을 지정합니다. 이 경우 파일과 디렉토리는 ec2-user 그룹에 속합니다.
        #hooks: 배포 중에 실행되는 작업을 정의하는 섹션입니다.

        #runas: 작업을 실행할 사용자를 지정합니다. 이 경우 작업은 ec2-user 사용자로 실행됩니다.
        #AfterInstall: 배포 중 AfterInstall 훅에서 실행할 작업 목록을 정의합니다.
        #location: 실행할 스크립트 또는 명령의 위치를 지정합니다. 이 경우 scripts/deploy.sh 스크립트를 실행합니다.
        #timeout: 작업이 실행될 최대 시간(초)을 지정합니다. 이 경우 작업이 60초 내에 완료되어야 합니다.